[WIP] `cleanup` handles Mac App Store apps via `mas`
- Initial explorations suggest this isn't possible. `mas uninstall`
  requires `sudo` and was very unreliable for me when I tried to
  uninstall 'Notion Web Clipper':

```
❯ mas list
[...]
1559269364  Notion Web Clipper  (1.0.3)

❯ mas uninstall 1559269364
Warning: Apps installed from the Mac App Store require root permission to remove.
Error: Unable to move app to trash.
Error: Uninstall failed

❯ sudo mas uninstall 1559269364
Error: Not installed
```